### ISSUE TITLE
Idk how to put my token in...

### ISSUE THREAD

**Issue by Shashwat4824G** [NoMeansNowastaken/KarutaSniper#15]
I did go through all the things properly but at the end when I run main.py it says "Improper token entered" or something like that. How to I put my token properly?
![image_2023-02-17_095709655](https://user-images.githubusercontent.com/49334511/219549344-2ae4de52-ee5a-4c55-af67-5aa2c25a9251.png)

**Comment by shrekisallah** [comment]
should work as long as config.json looks like this
```token = "your token here",```

**Comment by Shashwat4824G** [comment]
ahh, I don't even know that what mistake I made Y_Y
