### ISSUE TITLE
where to enter the path of pytesseract

### ISSUE THREAD

**Issue by ArshKshatriya** [NoMeansNowastaken/KarutaSniper#17]
**Describe the bug**
A clear and concise description of what the bug is. (with errors if any)

**Other information:**
 - Os
 - Version [e.g. 1.2] (shows on startup)
**Additional context**

**Comment by ArshKshatriya** [comment]
Import "Image" could not be resolved what do i do?

**Comment by shrekisallah** [comment]
```pip install pillow```

**Comment by ArshKshatriya** [comment]
already done yet showing same thing but in ocr.py line 6  It's still the same plus where should i add the path of pytesseract

**Comment by shrekisallah** [comment]
for the pytesseract path read through the comments in this issue: #7

**Comment by shrekisallah** [comment]
for the "import image" issue, its most an issue specific to your computer, so i can't help you there, but google can

**Comment by ArshKshatriya** [comment]
> for the pytesseract path read through the comments in this issue: #7

got it but can't figure out which line do i need to add it to

**Comment by NoMeansNowastaken** [comment]
maybe line 15?

**Comment by ArshKshatriya** [comment]
any way to contact you since is doesn't work the codes runs also says found anime but never drops or grabs

**Comment by shrekisallah** [comment]
https://github.com/NoMeansNowastaken/KarutaSniper#contact-me
