### ISSUE TITLE
main py file isnt working

### ISSUE THREAD

**Issue by happygeeked** [NoMeansNowastaken/KarutaSniper#23]
entered my token already, setup keywords, tried using the install like 20 times now but nothing is working, reinstalled, i have all of the requirements but still whenever i open the mian py file it just closes instantly, tried on different versions of python aswell. nothing is working to fix my issue and i still can't open the main py file,

**Comment by shrekisallah** [comment]
Its throwing an error; run from command prompt instead of directly and it should tell you the error.
