### ISSUE TITLE
Has no attribute errors

### ISSUE THREAD

**Issue by Zyzy69** [NoMeansNowastaken/KarutaSniper#24]
I'm getting many api has no attribute issomething or filewatch errors what to do?

**Comment by shrekisallah** [comment]
you didnt add tesseract to your path see issue #7 on how to add it

**Comment by Zyzy69** [comment]
I already added it to path, but it's still throwing the same error
![image](https://github.com/NoMeansNowastaken/KarutaSniper/assets/77783543/ea4652c8-11a8-4277-813e-aec989ce4be7)

**Comment by zewryy** [comment]
i have same problem ( i added to path tesseract) 
![image](https://github.com/NoMeansNowastaken/KarutaSniper/assets/135257130/cbef7339-b2eb-494a-8709-6b7bf41986da)

**Comment by shrekisallah** [comment]
oops... just realized a pull req deleted the required modules
ill fix it when home
