### ISSUE TITLE
Issue with an attribute 

### ISSUE THREAD

**Issue by razorthi** [NoMeansNowastaken/KarutaSniper#26]
The clicking on buttons often gives out an error 
```
Traceback (most recent call last):
  File "C:\Users\thilo\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 600, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\thilo\Desktop\KarutaSniper-master\main.py", line 410, in on_message
    await self.buttons[i].click()
  File "C:\Users\thilo\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\components.py", line 243, in click
    return await _wrapped_interaction(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thilo\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\interactions.py", line 203, in _wrapped_interaction
    await state.http.interact(type, data, channel, nonce=nonce, **kwargs)
  File "C:\Users\thilo\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\http.py", line 934, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In data: Component validation failed 

```
![Screenshot 2024-01-19 174807](https://github.com/NoMeansNowastaken/KarutaSniper/assets/97787406/68885151-366e-48ea-aa16-e723df0e39bc)

it did work once in the try to get an error code for this to report. 
Also, something I may add is that the adding of reactions is working fairly well for me.
I tried to find a solution myself but since I'm not as proficient as you i didn't find a solution.

**Comment by razorthi** [comment]
![image](https://github.com/NoMeansNowastaken/KarutaSniper/assets/97787406/3875f22b-d027-49a6-bb60-f3a77d8907fb)
here is another example of the error

**Comment by razorthi** [comment]
![image](https://github.com/NoMeansNowastaken/KarutaSniper/assets/97787406/3cb9db25-4dfa-41bf-af3e-1f25428a1eed)
and here it actually clicked the button (i had cooldown so no collect)

**Comment by razorthi** [comment]
![image](https://github.com/NoMeansNowastaken/KarutaSniper/assets/97787406/452b440c-a89e-4dd2-97c3-34075bac437c)
here is a longer error

**Comment by astolfoismywaifu** [comment]
Use a smaller server

**Comment by razorthi** [comment]
> Use a smaller server

I kinda found that out myself by now. Was hoping there would be a way to work around this.
Ty anyway.

**Comment by astolfoismywaifu** [comment]
@razorthi this should be fixed with the latest update

**Comment by razorthi** [comment]
@astolfoismywaifu I would like to say that it helped but i think it got worse for me

**Comment by astolfoismywaifu** [comment]
> @astolfoismywaifu I would like to say that it helped but i think it got worse for me. I cant even really start it anymore (get stuck before working)
> 
> ![image](https://private-user-images.githubusercontent.com/97787406/308215562-95c4f0aa-d872-4a91-96aa-ee3c7b279637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTIxNzMsIm5iZiI6MTcwOTA1MTg3MywicGF0aCI6Ii85Nzc4NzQwNi8zMDgyMTU1NjItOTVjNGYwYWEtZDg3Mi00YTkxLTk2YWEtZWUzYzdiMjc5NjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE2Mzc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYWM1MjYzYWIwNDI1NGE5ZmE1NzMzNGIwNzAxYzdiODhiNDJhNzJjOTNhNDBlZTdhMjdjNzkzOTE1ZmI1YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QJDPluaOpEYCa9Xh3IYc2jO8_6Jchu6RTTm76gSGLm0)

Did you update discord.py-self? It needs the latest dev version to work.
```pip install git+https://github.com/dolfies/discord.py-self.git```

**Comment by razorthi** [comment]
> > @astolfoismywaifu I would like to say that it helped but i think it got worse for me. I cant even really start it anymore (get stuck before working)
> > ![image](https://private-user-images.githubusercontent.com/97787406/308215562-95c4f0aa-d872-4a91-96aa-ee3c7b279637.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTIxNzMsIm5iZiI6MTcwOTA1MTg3MywicGF0aCI6Ii85Nzc4NzQwNi8zMDgyMTU1NjItOTVjNGYwYWEtZDg3Mi00YTkxLTk2YWEtZWUzYzdiMjc5NjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE2Mzc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjYWM1MjYzYWIwNDI1NGE5ZmE1NzMzNGIwNzAxYzdiODhiNDJhNzJjOTNhNDBlZTdhMjdjNzkzOTE1ZmI1YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QJDPluaOpEYCa9Xh3IYc2jO8_6Jchu6RTTm76gSGLm0)
> 
> Did you update discord.py-self? It needs the latest dev version to work. `pip install git+https://github.com/dolfies/discord.py-self.git`

Yeah i did and It didnt work... I somehoe fixed it now. I just reinstalled everything (even python). Anyway its working now and I thank you for your help!
