### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by SkylinerzEx** [NoMeansNowastaken/KarutaSniper#3]
Is there a specific python version that is compatible with this? I used 3.9, and it was unable to detect the token and cmd closed instantly

**Comment by NoMeansNowastaken** [comment]
3.9 should work
could you paste whatever error cmd is showing?
also did you install requirements

**Comment by SkylinerzEx** [comment]
I managed to troubleshoot, it was just errors on my end, and errors about pytesseract script not pointing to correct path for the exe. 

Are you looking into ways to have the option to detect only on cards with certain frames (signifying rarity)

I also have an idea to use the karuta bot dm to { k!lu [card name] [anime title] } and get the wishlist value, set a threshold and help in deciding whether to hunt for the cards. 

Currently if the bot detects cards with same anime, it can't really decide which is the higher priority.

**Comment by shrekisallah** [comment]
Detecting frames has been thought about but I currently don't know of any software or library that can do that.

**Comment by shrekisallah** [comment]
If you more suggestions feel free to discuss them, as I am open to any ideas.
