### ISSUE TITLE
The bot does not react to the buttons

### ISSUE THREAD

**Issue by Scrp08** [NoMeansNowastaken/KarutaSniper#7]
The bot reacts to the reactions but not to the buttons, there is no error and it detects the anime but it just does nothing when it finds a card

**Comment by shrekisallah** [comment]
If its error 400, its a problem that I've tried to fix, and searched everywhere for an answer, but couldn't find a solution. For now buttons won't work until I have a lot of free time.

**Comment by Scrp08** [comment]
The cmd just doesn't show any errors but the script doesn't work for buttons, I tried to fix it by searching and trying on my own but nothing makes the button reactions work, I even tried asking ChatGPT to help fix it but it doesn't work

**Comment by Scrp08** [comment]
A little quote, I had to add this to main.py for the script to work

`pytesseract.pytesseract.tesseract_cmd = 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'`

**Comment by shrekisallah** [comment]
hmm I might add that if tesseract isnt in path by default and i have no idea why the buttons behave the way they do

**Comment by EvilEpicPanda** [comment]
> A little quote, I had to add this to main.py for the script to work
> 
> `pytesseract.pytesseract.tesseract_cmd = 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'`

![image](https://user-images.githubusercontent.com/20939715/217976505-f00b9071-6dc2-496b-b39b-9449aaf7b85c.png)
Are you sure you added it to your path?
